### PR TITLE
Update for version 0.8.0

### PR DESCRIPTION
**Pull request by cnweaver**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
~* [ ] Bumped the build number (if the version is unchanged)~
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Review by myNameIsPatrick — APPROVED** [review]
Looks fine, but I don't understand why you're opening up these PRs manually. They should be automatically created by the bot, typically in a few hours or so.

**Comment by cnweaver** [comment]
Our release checklist (e.g. https://github.com/scimma/hop-client/issues/196) says to do it directly, and it's faster than waiting for the bot, which has been days late in some cases, if I remember correctly.

**Comment by cnweaver** [comment]
@conda-forge-admin, please rerender

**Comment by myNameIsPatrick** [comment]
> Our release checklist (e.g. [scimma/hop-client#196](https://github.com/scimma/hop-client/issues/196)) says to do it directly, and it's faster than waiting for the bot, which has been days late in some cases, if I remember correctly.

Huh, okay. I wasn't involved in writing that, so wasn't aware of it. That's fine, can I request you clean up the bot-generated PRs when they involve making releases that are no longer relevant? They'll tend to pile up otherwise.

**Comment by cnweaver** [comment]
Will do.

**Pull request merged**
